#pragma once

enum {
    BASEBAND_SINK_IFACE_CMD_GET_MODE,
    BASEBAND_SINK_IFACE_CMD_SET_MODE,
    BASEBAND_SINK_IFACE_CMD_START,
    BASEBAND_SINK_IFACE_CMD_STOP
};

enum {
    BASEBAND_SINK_MODE_BASEBAND,
    BASEBAND_SINK_MODE_AUDIO
};